### ISSUE TITLE
Make fake data and biased ML model

### ISSUE THREAD

**Issue by gaborcsapo** [AliaElKattan/survivalofthebestfit#10]

**Comment by jihjihk** [comment]
Attributes as of now: name, personal objective, skill, school prestige, work exp, ambition and **color**

We can make it so that yellow is more strongly associated with better school prestige. Although I feel like we need to replace either skill or work exp with an attribute that is less relevant to the actual work (equal to gender/sexual orientation/race in real life)

**Comment by jihjihk** [comment]
some ideas could be...number of teeth....

**Comment by jihjihk** [comment]
Decided on the `sum(attributes) = employability`
